### ISSUE TITLE
What can JavaScript do? - 20.09 от 18:00

### ISSUE THREAD

**Issue by mgechev** [SofiaJavaScript/events#1]
# What can JavaScript do? - 20.09 от 18:00
## Събитието

[SofiaJS](https://github.com/SofiaJavaScript), съвместно с Хак България представят събитието **"What can JavaScript do?"**

Ще съберем 4 човека, които имат какво да кажат и покажат - приложения, разчитащи предимно на JavaScript - било то Frontend, Компютърна графика или NodeJS backend.

Всеки ще има 15 минути, в рамките на които да:
- Направи демо.
- Разкаже повече за архитектурата на приложението.
- И покаже код.

Вечерта след събитието, ще продължим с 3тото издание на [BeerJS (от 20:00)](https://github.com/beerjs/sofia/issues/3) - ще се преместим в Бирария Петте Кьошета, за да изпием и по някоя друга бира.

Събитието е и първото издание на поредицата от събития "What can **X** do?", организирани от Хак България.
## Пространствени и Часови рамки

Събитието ще се състои на 20.09 (събота) от 18:00 в [залата на Хак България](https://www.google.bg/maps/place/Hack+Bulgaria/@42.64774,23.384747,17z/data=!3m1!4b1!4m2!3m1!1s0x40aa86ed287d5e33:0x315f162015dedaa3?hl=en).

Общ капацитет - 50 човека.
За да присъствате, моля цъкнете attending във Facebook - https://www.facebook.com/events/1467468013514060/
## Участници и Програма

Програмата се обновява - ако бройката на лекторите не е 4, погледнете пак след известно време.
### Минко Гечев

Freelance, занимаващ се с разработка и консултантска дейност. В момента работи по няколко проекта, сред които real-time web приложение за Интернет обучение. В свободното си време се стреми да поддържа open-source проектите си, да води лекции в курса "Advanced JavaScript" във ФМИ, да публикува интересна информация в блога си и да спортува.
- [GitHub](https://github.com/mgechev)
- [Twitter](https://twitter.com/mgechev)
- [Blog](http://blog.mgechev.com)

По време на събитието ще демонстрира използване на нови browser APIs, сред които WebSockets, WebRTC & HTML5 Canvas.
### Борис Симандов

Софтуерен евангелист и предприемач с повече от 20 години опит в областта на софтуерния дизайн, архитектура, код оптимизации и разпределени мрежови системи. 

В момента е продуктов мениджър за V-Ray Cloud и V-Ray Application SDK за C++/Java/.Net/Node.js/Python  в Хаос Груп. Има специални интереси във внедряването на cutting-edge технологии и запазването на качеството, чистотата и скоростта на кода.
- [Twitter](https://twitter.com/simandoff)

**Боби ще покаже Large scale JavaScript Applications и малко Tip and Tricks using Node.js**
### Никола Димитров

Game dev ентусиаст с твърде много свободно време, което понякога отива за създаване на графични демота.

В момента разработва 3D игра по романа "Под Игото" (също с JS арсенала), която можете да видите тук - http://thralldom.net

Ще покаже основно фрактали и други видове процедурно рисуване.
- [Blog](http://dimitroff.bg)
- [GitHub](http://github.com/nikoladimitroff)
### Иван Георгиев (Джо)

Бивш състезател по информатика с бронз от Международната олимпиада по информатика и първо място на Републиканската по програмиране (заедно с [Иван](https://www.linkedin.com/pub/ivan-todorov/39/40b/835) и [Стефан](https://www.linkedin.com/pub/stefan-avramov/59/933/3b4)) . Има опит в компании като Google, Facebook, SoundCloud и Хаос Груп.

Напоследък се интересува предимно от Distributed Computing и Machine Learning. Като страничен ефект от работата си с Борис Симандов в Хаос Груп, има интерес и от развитието на JavaScript.

**Иван ще ви покаже как да накарате JavaScript приложенията си да "мислят", използвай един от най-нашумелите похвати в областта на машинното самообучение в последните няколко години.**

Може да намерите Джо в:
- [GitHub](https://github.com/IvanVergiliev)
- [Twitter](https://twitter.com/IvanVergiliev)

**Comment by RadoRado** [comment]
http://blog.hackbulgaria.com/what-can-javascript-do-materials/ !
